const data = {
  products: [
    {
      _id: "1",
      name: "Raymond Royel",
      category: "Shirts",
      image: "/images/product1.jpg",
      price: 350,
      countInStock: 10,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 20,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "IndoPrime khaki shirt",
      category: "Shirts",
      image: "/images/product2.jpg",
      price: 185,
      countInStock: 20,
      brand: "IndoPrime",
      rating: 4,
      numReviews: 25,
      description: "Medium quality product",
    },
    {
      _id: "3",
      name: "EYEBOGLER Ninja",
      category: "Shirts",
      image: "/images/product3.jpg",
      price: 115,
      countInStock: 0,
      brand: "EYEBOGLER",
      rating: 3.5,
      numReviews: 52,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "MYZA short",
      category: "Pants",
      image: "/images/product4.jpg",
      price: 199,
      countInStock: 15,
      brand: "MYZA",
      rating: 4.5,
      numReviews: 203,
      description: "Avg quality product",
    },
    {
      _id: "5",
      name: "PAUSE Noob",
      category: "Pants",
      image: "/images/product5.jpg",
      price: 99,
      countInStock: 5,
      brand: "PAUSE",
      rating: 3,
      numReviews: 35,
      description: "Low quality product",
    },
    {
      _id: "6",
      name: "AMZIRA Gray",
      category: "Pants",
      image: "/images/product6.jpg",
      price: 165,
      countInStock: 12,
      brand: "AMZIRA",
      rating: 4,
      numReviews: 90,
      description: "Medium quality product",
    },
  ],
};

export default data;
